plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.example.filesercher'
    compileSdk 34

    defaultConfig {
        applicationId "com.example.filesercher"
        minSdk 26
        targetSdk 34
        versionCode 7 // Поднимаем до 7 для полной очистки кэша на телефоне
        versionName "7.0"
    }

    // Этот блок автоматически допишет все нужные права и настройки в манифест при сборке
    applicationVariants.all { variant ->
        variant.outputs.all { output ->
            output.processManifestProvider.get().doLast { task ->
                def manifestFile = task.manifestOutputFile.get().asFile
                if (manifestFile.exists()) {
                    def text = manifestFile.text
                    
                    // Внедряем разрешения на работу с файлами
                    text = text.replace("<manifest", "<manifest xmlns:android=\"http://android.com\"")
                    text = text.replace("</manifest>", "<uses-permission android:name=\"android.permission.READ_EXTERNAL_STORAGE\" /><uses-permission android:name=\"android.permission.WRITE_EXTERNAL_STORAGE\" /><uses-permission android:name=\"android.permission.MANAGE_EXTERNAL_STORAGE\" /></manifest>")
                    
                    // Внедряем настройки ярлыка, имени и экспорта активности
                    text = text.replace("<application>", "<application android:allowBackup=\"true\" android:label=\"Fils ME ᴘʀᴏᴊᴇᴄᴛ\" android:theme=\"@android:style/Theme.DeviceDefault.NoActionBar\">")
                    text = text.replace("<activity android:name=\"com.example.filesercher.MainActivity\">", "<activity android:name=\"com.example.filesercher.MainActivity\" android:exported=\"true\">")
                    
                    manifestFile.text = text
                }
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.12.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.documentfile:documentfile:1.0.1'
}
