name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Скачиваем и настраиваем правильную, современную версию Gradle 8.5
    - name: Install Correct Gradle 8.5
      run: |
        wget -q https://gradle.org
        sudo unzip -q gradle-8.5-bin.zip -d /opt
        echo "/opt/gradle-8.5/bin" >> $GITHUB_PATH

    - name: Build with Gradle
      run: gradle assembleDebug --no-daemon

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
        
